ServerConfig:
  AppVersion: 1.0.0
  Mode: Development
  RoutePrefix: /api/v1/basket-service-api
  Debug: false
  Port: 8080
  TimeoutSecs: 60
  ReadTimeoutSecs: 60
  WriteTimeoutSecs: 12

JWTConfig:
  SessionTime: 3600
  SecretKey: dummySecretKey

DBConfig:
  DataSourceName: postgres://postgres:Password@localhost:5432/Final_Project_db?sslmode=disable
  MaxOpen: 50
  MaxIdle: 50
  MaxLifetime: 5


Logger:
  Development: true
  Encoding: json
  Level: error